- name: variable preference 
  hosts: local
  connection: local
  vars:
    NAME: "vars from paly"
  vars_files:
  - cource.yaml
  vars_prompt:
  - name: NAME
    prompt: Please enter the name
    private: false

  tasks:
  - name: print name
    vars:
      NAME: "Vars from TASK"
    ansible.builtin.debug:
      msg: "HI {{ NAME }}"