- name: instaling packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: # list of string datatypes
    - nginx # string data types
    - mysql
    - zip