- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: shell, linux, ansible, terraform
    tags:
      name: ansible
      project: roboshop
      component: catalogue
    tagsList: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]
  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: " HI Narendra, {{ GREETING | default('good morning') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tagsList | items2dict }}"

  - name: read student yaml
    ansible.builtin.debug:
      msg: "{{ lookup( 'file', 'student.yaml' ) | from_yaml }}"